# Generated by Django 2.2.28 on 2022-07-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=45, unique=True)),
                ('sha256', models.CharField(max_length=65, unique=True)),
                ('cert_sha1', models.CharField(max_length=45)),
                ('packagename', models.CharField(max_length=300)),
                ('sdkversion', models.CharField(blank=True, max_length=45, null=True)),
                ('targetsdkversion', models.CharField(blank=True, max_length=45, null=True)),
                ('versionname', models.CharField(blank=True, max_length=150, null=True)),
                ('versioncode', models.CharField(blank=True, max_length=100, null=True)),
                ('vender', models.CharField(max_length=45)),
                ('source', models.CharField(max_length=45)),
                ('checkdelete', models.CharField(max_length=45)),
                ('xmldamage', models.CharField(max_length=45)),
                ('insertdate', models.CharField(max_length=45)),
                ('modifieddate', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'blacklist',
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=45, unique=True)),
                ('sha256', models.CharField(max_length=65)),
                ('cert_sha1', models.CharField(max_length=45)),
                ('packagename', models.CharField(max_length=300)),
                ('sdkversion', models.CharField(blank=True, max_length=45, null=True)),
                ('targetsdkversion', models.CharField(blank=True, max_length=45, null=True)),
                ('versionname', models.CharField(blank=True, max_length=150, null=True)),
                ('versioncode', models.CharField(blank=True, max_length=100, null=True)),
                ('vender', models.CharField(max_length=45)),
                ('source', models.CharField(max_length=45)),
                ('checkdelete', models.CharField(max_length=45)),
                ('xmldamage', models.CharField(max_length=45)),
                ('malwarecert', models.CharField(max_length=45)),
                ('insertdate', models.CharField(max_length=45)),
                ('modifieddate', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'whitelist',
            },
        ),
    ]
